name: isochrone_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - streamlit=1.12.0
  - pandas=1.4.2
  - geopandas=0.10.2
  - requests=2.26.0
  - matplotlib=3.5.1
  - shapely=1.8.0
  - python-dotenv=0.20.0

# Optional: Include pip dependencies if needed
#  - pip:
#    - any_other_package==version_number
